kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-k8s-frontend
  labels:
    app: hello-k8s-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s-frontend
  template:
    metadata:
      labels:
        app: hello-k8s-frontend
    spec:
      containers:
      - name: hello-k8s-frontend
        image: hello-k8s-frontend
        imagePullPolicy: IfNotPresent
        env:
          - name: BACKEND
            value: http://hello-k8s-backend.default.svc.cluster.local:4569
        ports:
          - containerPort: 4567
